name: coverage
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}