name: coverage
on: [ push ]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}