name: coverage
on: [ push ]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install lcov
        run: |
          sudo apt-get install -y lcov
          sudo gem install coveralls-lcov
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.github_token }}