name: coverage
on: [ push ]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          run: gem install coveralls-lcov
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.github_token }}