name: CI
on: [ push ]
jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: test
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make ./tests
          ./tests

      - name: install lcov and gcovr
        run: |
          sudo pip install --user cpp-coveralls
          sudo apt-get install -y lcov

      - name: run lcov
        run: | 
          ls
          lcov --capture --directory . --output-file lcov.info
          ls

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "./lcov.info"
          github-token: ${{ secrets.github_token }}