name: CI
on: [ push ]
jobs:
  Building and testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make
      - name: test
        shell: bash
        run: |
          ./tests