name: CI
on: [ push ]
jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        shell: bash
        run: |
          cmake -B build
          cd build
          make
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          apt install googletest
          cd build
          ./tests